name: Build

on:
  push:
    tags:
      - 'v*'
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "GIT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - run: make build
      - uses: softprops/action-gh-release@v1
        with:
          files: lens-k8s-proxy-linux-amd64
  macos:
    runs-on: macos-10.15
    strategy:
      matrix:
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "GIT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - run: make build
        env: 
          GOARCH: ${{ matrix.goarch }}
      - uses: softprops/action-gh-release@v1
        with:
          files: lens-k8s-proxy-darwin-${{ matrix.goarch }}
  windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "GIT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - run: make build
      - uses: softprops/action-gh-release@v1
        with:
          files: lens-k8s-proxy-windows-amd64