name: Build

on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
            RUNNER_OS: linux
          - os: macos-10.15
            RUNNER_OS: macos
          - os: windows-201
            RUNNER_OS: windows
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - run: make build
        env:
          GOARCH: ${{ matrix.goarch }}
          VERSION: ${{ github.ref_name }}
      - uses: softprops/action-gh-release@v1
        with:
          files: lens-k8s-proxy-${{ matrix.RUNNER_OS }}-${{ matrix.goarch }}
